[workspace]
authors = ["Sangeetha <an.sangeetha@gmail.com>"]
channels = ["conda-forge"]
name = "Intro to Python for Scientists - Jun 2025"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.0,<3"
seaborn = ">=0.13.2,<0.14"
pip = ">=25.1.1,<26"
